---
apiVersion: v1
kind: config
spec:
  mdm: # Controls added to "No team"
    macos_settings:
      custom_settings:
      - ./lib/os-updates.ddm.json
      - ./lib/password.macos.mobileconfig
  scripts: # Scripts available to run on "No team"
  queries: # Queries added to hosts all teams
  - ./lib/collect-fleetd-update-channel.queries.yml
  policies: # Policies added to all teams
  agent_options:
    command_line_flags: {}
    config:
      decorators:
        load:
        - SELECT uuid AS host_uuid FROM system_info;
        - SELECT hostname AS hostname FROM system_info;
      options:
        disable_distributed: false
        distributed_interval: 5
        distributed_plugin: tls
        distributed_tls_max_attempts: 3
        logger_tls_endpoint: /api/v1/osquery/log
        pack_delimiter: /
    overrides:
      platforms:
        darwin:
          auto_table_construction:
            chrome_browser_history:
              columns:
              - id
              - url
              - title
              - visit_count
              - type_count
              - last_visit_time
              - hidden
              - visit_time
              - from_visit
              - visit_duration
              - transition
              - source
              path: /Users/%/Library/Application Support/Google/Chrome/%/History
              query: SELECT urls.id id, urls.url url, urls.title title, urls.visit_count
                visit_count, urls.typed_count typed_count, urls.last_visit_time last_visit_time,
                urls.hidden hidden, visits.visit_time visit_time, visits.from_visit
                from_visit, visits.visit_duration visit_duration, visits.transition
                transition, visit_source.source source FROM urls JOIN visits ON urls.id
                = visits.url LEFT JOIN visit_source ON visits.id = visit_source.id
            tcc_system_entries:
              columns:
              - service
              - client
              - allowed
              - prompt_count
              - last_modified
              path: /Library/Application Support/com.apple.TCC/TCC.db
              query: select service, client, allowed, prompt_count, last_modified
                from access
        windows:
          auto_table_construction:
            chrome_browser_history:
              columns:
              - id
              - url
              - title
              - visit_count
              - type_count
              - last_visit_time
              - hidden
              - visit_time
              - from_visit
              - visit_duration
              - transition
              - source
              path: C:\Users\%\AppData\Local\Google\Chrome\User Data\%\History
              query: SELECT urls.id id, urls.url url, urls.title title, urls.visit_count
                visit_count, urls.typed_count typed_count, urls.last_visit_time last_visit_time,
                urls.hidden hidden, visits.visit_time visit_time, visits.from_visit
                from_visit, visits.visit_duration visit_duration, visits.transition
                transition, visit_source.source source FROM urls JOIN visits ON urls.id
                = visits.url LEFT JOIN visit_source ON visits.id = visit_source.id
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings:
    host_expiry_enabled: false
    host_expiry_window: 7
  integrations:
    jira: null
    zendesk: null
  mdm:
    apple_bm_default_team: "\U0001F4BB Workstations"
    apple_bm_enabled_and_configured: true
    apple_bm_terms_expired: false
    enabled_and_configured: true
    end_user_authentication:
      entity_id: https://fleetdm.example.com
      idp_name: Okta
      issuer_uri: ""
      metadata: ""
      metadata_url: https://okta.com/example
    macos_migration:
      enable: true
      mode: voluntary
      webhook_url: https://tines.com/example
    macos_settings:
      custom_settings: null
      enable_disk_encryption: true
    macos_setup:
      bootstrap_package: ""
      enable_end_user_authentication: false
      macos_setup_assistant: null
    macos_updates:
      deadline: "2023-06-12"
      minimum_version: 13.4.0
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url: ""
    org_name: Fleet Device Management
  server_settings:
    debug_host_ids:
    - 1
    - 3
    deferred_save_host: false
    enable_analytics: true
    live_query_disabled: false
    server_url: https://dogfood.fleetdm.com
  vulnerability_settings:
    databases_path: ""
  webhook_settings:
    failing_policies_webhook:
      destination_url: https://tines.com/example
      enable_failing_policies_webhook: true
      host_batch_size: 0
      policy_ids:
      - 136
      - 178
    host_status_webhook:
      days_count: 1
      destination_url: ""
      enable_host_status_webhook: false
      host_percentage: 25
    interval: 1m0s
    vulnerabilities_webhook:
      destination_url: https://tines.com/example
      enable_vulnerabilities_webhook: false
      host_batch_size: 0