#!/bin/sh

# Fleet extracts and saves package IDs.
pkg_ids=(
  "com.marvelapp.MarvelAuth"
  "org.sparkle-project.Sparkle"
  "com.swiftyjson.SwiftyJSON"
  "com.potionfactory.LetsMove"
  "com.omaralbeik.UserDefaultsStore"
  "com.apollographql.ApolloAPI.macosx"
  "com.marvelprototyping.graphql"
  "com.roymarmelstein.Zip"
  "org.sparkle-project.Sparkle.Updater"
  "com.marvelprototyping.marvelsketchframework"
  "com.jpsim.Yams"
  "org.alamofire.Alamofire"
  "org.sparkle-project.DownloaderService"
  "com.marvelprototyping.sketchplugin"
  "com.marvelprototyping.easelmodels"
  "com.marvelprototyping.marvelmacos"
  "com.marvelprototyping.SketchModels"
  "org.sparkle-project.InstallerLauncher"
  "$(PRODUCT_BUNDLE_IDENTIFIER)"
  "com.apollographql.Apollo.macosx"
  "com.apollographql.ApolloUtils.macosx"
  "com.wolfrosch.Gzip"
  "com.marvelprototyping.Heap"
  "com.marvelprototyping.shapeshifter"
  "uk.co.joylordsystems.Reachability"
  "io.radex.SwiftyTimer"
  "com.marvelprototyping.SketchTool"
  "com.krzyzanowskim.CryptoSwift"
)

# For each package id, get all .app folders associated with the package and remove them.
for pkg_id in "${pkg_ids[@]}"
do
  # Get volume and location of the package.
  volume=$(pkgutil --pkg-info "$pkg_id" | grep -i "volume" | awk '{if (NF>1) print $NF}')
  location=$(pkgutil --pkg-info "$pkg_id" | grep -i "location" | awk '{if (NF>1) print $NF}')
  # Check if this package id corresponds to a valid/installed package
  if [[ ! -z "$volume" ]]; then
    # Remove individual directories that end with ".app" belonging to the package.
    # Only process directories that end with ".app" to prevent Fleet from removing top level directories.
    pkgutil --only-dirs --files "$pkg_id" | grep "\.app$" | sed -e 's@^@'"$volume""$location"'/@' | tr '\n' '\0' | xargs -n 1 -0 rm -rf
    # Remove receipts
    pkgutil --forget "$pkg_id"
  else
    echo "WARNING: volume is empty for package ID $pkg_id"
  fi
done
