---
apiVersion: v1 
kind: query 
spec: 
  team: Workstations
  name: Get serial number of a laptop 
  description: Returns the serial number of a laptop, which can be useful for asset tracking.
  query: SELECT hardware_serial FROM system_info; 
  interval: 3600 # 1 hour
  observer_can_run: true
  automations_enabled: false
--- 
apiVersion: v1 
kind: query 
spec: 
  team: Workstations
  name: Get recently added or removed USB drives 
  description: Report event publisher health and track event counters. 
  query: |-
    SELECT action, DATETIME(time, 'unixepoch') AS datetime, vendor, mounts.path 
    FROM disk_events 
    LEFT JOIN mounts 
      ON mounts.device = disk_events.device
    ;
  interval: 86400 # 24 hours
  observer_can_run: false
  min_osquery_version: 5.4.0 # minimum osqueryd version
  platform: darwin
  automations_enabled: true
  logging: differential_ignore_removals # either "snapshot" (default), "differential", or "differential_ignore_removals"
